trigger:
  branches:
    include:
    - master
    - main
    - develop

schedules:
  - cron: "0 0 * * *"  # Bu örnek her gün gece yarısında bir tetikleme yapar. Cron zamanlamasını ihtiyacınıza göre ayarlayın.
    displayName: Daily midnight build
    branches:
      include:
      - master
      - main
      - develop
    always: true  # Bu, belirtilen dallarda değişiklik olmasa bile tetiklemenin her zaman gerçekleşeceği anlamına gelir.

pool:
  name: 'Default'

steps:
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: ''  # Burada bir scheme ismi belirtmeniz gerekebilir.
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/*.xcodeproj'  # Eğer bir workspace kullanmıyorsanız, burayı projenizin adıyla değiştirin.
    xcodeVersion: 'default'  # Seçenekler: 8, 9, 10, 11, 12, default, specifyPath

