# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
  branches:
    include:
    - master
    - main
    - develop

pool:
  name: 'Default'

steps:
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: ''  # Burada bir scheme ismi belirtmeniz gerekebilir.
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/*.xcodeproj'  # Eğer bir workspace kullanmıyorsanız, burayı projenizin adıyla değiştirin.
    xcodeVersion: 'default'  # Options: 8, 9, 10, 11, 12, default, specifyPath
